### ISSUE TITLE
ordered_abi fails for contracts with empty body

### ISSUE THREAD

**Issue by federicobond** [trufflesuite/truffle-solidity-utils#1]
[This line](https://github.com/trufflesuite/truffle-solidity-utils/blob/ac57620380c4debd36d15b3999b29060e93d3259/index.js#L31) throws an TypeError if body is null, which is the case when you currently write:

```
contract MyContract { }
``` 
This happens because `solidity-parser` doesn't guarantee that there will be a non-null value for the `body` key of a `ContractStatement` node.

Arguably, this is something that should be fixed at the parser level, as it seems reasonable to expect an empty array instead of null when there are no elements in it. Nevertheless, I am posting it here since ultimately either this code or its dependency should be updated to fix this bug.

**Comment by tcoulter** [comment]
This is fixed in #2. Will go out with our next release in a week or so.

**Comment by tcoulter** [comment]
Thanks!
